-- MySQL Script generated by MySQL Workbench
-- 2014年10月09日 星期四 10时32分12秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wxshop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wxshop` ;

-- -----------------------------------------------------
-- Schema wxshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wxshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wxshop` ;

-- -----------------------------------------------------
-- Table `wxshop`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wxshop`.`user` ;

CREATE TABLE IF NOT EXISTS `wxshop`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '用户主键\n',
  `open_id` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT '在微信中表示open_id，手机浏览器生成后填入',
  `phone` VARCHAR(45) NOT NULL COMMENT '用户手机号码，也是登陆账号',
  `password` VARCHAR(45) NOT NULL COMMENT '密码',
  `name` VARCHAR(45) NOT NULL COMMENT '用户名',
  `sex` TINYINT(1) NOT NULL COMMENT '性别',
  `address` VARCHAR(45) NOT NULL COMMENT '用户地址',
  `time` INT(11) NOT NULL COMMENT '注册时间',
  `status` SMALLINT(6) NOT NULL DEFAULT 0 COMMENT '０：注册但未激活，１：账号激活且可用，-1：账号被禁用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `wxshop`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wxshop`.`admin` ;

CREATE TABLE IF NOT EXISTS `wxshop`.`admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '管理员名',
  `password` VARCHAR(45) NOT NULL COMMENT '密码',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '管理员表';


-- -----------------------------------------------------
-- Table `wxshop`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wxshop`.`store` ;

CREATE TABLE IF NOT EXISTS `wxshop`.`store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL COMMENT '店名',
  `intro` VARCHAR(45) NOT NULL COMMENT '商家简介',
  `shoper_name` VARCHAR(45) NOT NULL COMMENT '商家名',
  `shoper_phone` VARCHAR(45) NOT NULL COMMENT '商家手机号码',
  `address` VARCHAR(45) NOT NULL COMMENT '商家所在地址',
  `time` INT(11) NOT NULL COMMENT '注册时间',
  `status` SMALLINT(6) NOT NULL COMMENT '０：注册但未激活，１：账号激活且可用，-1：账号被禁用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '商家表';


-- -----------------------------------------------------
-- Table `wxshop`.`goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wxshop`.`goods` ;

CREATE TABLE IF NOT EXISTS `wxshop`.`goods` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `store_id` INT(11) NOT NULL COMMENT '对应store表的id',
  `name` VARCHAR(45) NOT NULL COMMENT '商品名',
  `type_id` INT(11) NOT NULL COMMENT '分类编号',
  `originalPrice` FLOAT NOT NULL COMMENT '原价',
  `retailPrice` FLOAT NOT NULL COMMENT '现价',
  `headerImg` VARCHAR(45) NOT NULL COMMENT '标题图',
  `description` VARCHAR(45) NOT NULL COMMENT '商品详情\n',
  `quantity` INT(11) NOT NULL COMMENT '产品数量',
  `remainingQuantity` INT(11) NOT NULL COMMENT '产品剩余量',
  `time` INT(11) NOT NULL COMMENT '上架时间',
  `status` TINYINT(1) NOT NULL COMMENT '０：下架，１：上架',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `wxshop`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wxshop`.`type` ;

CREATE TABLE IF NOT EXISTS `wxshop`.`type` (
  `id` INT NOT NULL COMMENT '分类id',
  `store_id` INT(11) NOT NULL COMMENT '所属商家',
  `name` VARCHAR(45) NOT NULL COMMENT '类别名',
  `time` VARCHAR(45) NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '商品分类表';


-- -----------------------------------------------------
-- Table `wxshop`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wxshop`.`cart` ;

CREATE TABLE IF NOT EXISTS `wxshop`.`cart` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `goods_id` INT(11) NOT NULL COMMENT '商品id',
  `time` INT(11) NOT NULL COMMENT '添加时间',
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '０：未处理，１：已处理',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '购物车';


-- -----------------------------------------------------
-- Table `wxshop`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wxshop`.`order` ;

CREATE TABLE IF NOT EXISTS `wxshop`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `goods_id` INT(11) NOT NULL COMMENT '商品id',
  `user_id` INT(11) NOT NULL COMMENT '用户id',
  `pay` FLOAT NOT NULL COMMENT '支付金额',
  `pay_status` TINYINT(1) NOT NULL COMMENT '０：尚未支付，１：支付完成',
  `store_status` TINYINT(1) NOT NULL COMMENT '０：收到订单尚未发货\n１：已发货',
  `time` INT(11) NOT NULL COMMENT '订单创建时间',
  `status` TINYINT(1) NOT NULL COMMENT '０：订单创建，交易尚未完成\n１：交易成功',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '订单表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
